### ISSUE TITLE
Implement window event listener

### ISSUE THREAD

**Issue by josephmilla** [project415x/project415x.github.io#62]
In order to make the different frames to talk to main window, Window.postmessage() must implement wherein it acts as a broadcaster to every element in the DOM that listens for events actively.

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

These might help:
http://stackoverflow.com/questions/18464635/detect-event-from-iframe-works-with-jquery-event-listener-on-parent-but-now-wit
http://stackoverflow.com/questions/6452502/adding-click-event-handler-to-iframe
http://javascript.info/tutorial/cross-window-messaging-with-postmessage

**Comment by zwang180** [comment]
(The same thing is in the google doc, I just add some notes about the links provided by Joseph and some documents about the method we are using.)

How it works: http://javascript.info/tutorial/cross-window-messaging-with-postmessage

Documents and References of related method(Syntax and Examples): 

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
Window.postMessage() (This method is used to post a custom message from the sending side to a desired destination. Also contains a nice example about how cross-window messaging are implemented.) 

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
EventTarget.addEventListener() (This method is used to add a listener to a specific event and react when that event is triggered. In this case, it is used at the receiving side to listen to the event “message”, i.e. the message sent by the sending side.)

https://developer.mozilla.org/en-US/docs/Web/Events
A Event Reference (Just a list of event type, pay attention to the  “message” event.)

Some related examples (Little bit hard to understand…):

http://stackoverflow.com/questions/6452502/adding-click-event-handler-to-iframe
Add click event handler to iFrame (Example about addEventListener() method.)

http://stackoverflow.com/questions/18464635/detect-event-from-iframe-works-with-jquery-event-listener-on-parent-but-now-wit
Detect event from iframe works with jQuery event listener on parent, but now with pure JS
(I didn’t quite understand this example, but it seems we can detect events other than “message” from the parent side. And this also provides us an option of using jQuery.)

Feel free to make changes and add comments, especially if you have any ideas about the second related examples… I will post anything that I think is useful.
