### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by josephmilla** [project415x/project415x.github.io#63]
It might be better to consider this as a milestone since there's a lot of moving components involved. These are the following that I think need to be considered:
- Make sure all of the elements that require no interaction at all are responsive to the changing viewports. This could be done by manually changing font, div sizes, or whatnot for different `@media` params
- The trickier part of this is the interactive components. Currently, the canvases are operating on 500 pixels x 500 pixels. There should be a way to make the canvases change its whole game engine on the given viewport size

**Comment by SkamDart** [comment]
Helpful
http://stackoverflow.com/questions/23445907/jquery-to-make-html5-canvas-responsive

**Comment by cmalk** [comment]
We'll see how well the OOP migration fixed this when levels 2 and 3 are re-coded in the new framework.
