### ISSUE TITLE
Create drop down menu to navigate to multiple games

### ISSUE THREAD

**Issue by SkamDart** [project415x/project415x.github.io#67]
@cmalk I'm a little unfamiliar with what the details of this is.. So go ahead and edit it.

**Comment by josephmilla** [comment]
I think they want the "GAME" tab to turn into a drop down menu wherein you could select "GAME 1", "GAME 2", etc

CC: @cmalk

**Comment by cmalk** [comment]
That's right, it would create a menu where you can select game 1 level 1, game 1 level 2, ..., game 2 level 1, etc.
