### ISSUE TITLE
OOP Approach 

### ISSUE THREAD

**Issue by SkamDart** [project415x/project415x.github.io#68]
Check @cmalk 's email for reference to the class structure. 
I'll be adding it in a comment after we have it solidified.

JavaScript has a prototypal inheritance which is very different from the classical inheritance used by OOP languages. 

Here are a couple good resources that explain the JS prototypal inheritance.
https://medium.com/@PitaJ/javascript-inheritance-patterns-179d8f6c143c#.3gavx438d
http://stackoverflow.com/questions/1645027/popular-javascript-inheritance-patterns
http://amzotti.github.io/javascript/2015/02/09/javascript-inheritance-patterns/
http://javascriptissexy.com/oop-in-javascript-what-you-need-to-know/

It can be very confusing so if you've got any questions, don't hesitate to email me. 

Also, https://github.com/airbnb/javascript is a FANTASTIC guide for JS style, or reference in case you forget how to do something!

**Comment by josephmilla** [comment]
:+1:
