### ISSUE TITLE
Break the drag functionality

### ISSUE THREAD

**Issue by SkamDart** [project415x/project415x.github.io#81]
### Hey all,

@TylerMulick @ruthluo91 @clairemerriman 

When you get the chance, run the follow commands below into your terminal to get the latest version of the code and try to break our drag functionality/find any flaws. If you do, please comment below with what the issue was and how we can reproduce it.  We are planning on modifying our goals for this week by a little :+1: because of this progress.

```
cd /path/to/project/repo
git checkout oop-migration
git pull
jekyll serve
```

Point your browser to localhost:4000/playground

Cheers! :tropical_drink:

**Comment by cmalk** [comment]
Looks great for me. Good work guys! Let me know when the "master importer" is done, then we can really start cleaning up and organizing this code. I'm getting really excited again.

**Comment by clairemerriman** [comment]
I played around with it last night and again today, and it worked great!

Best,

Claire

On Feb 24, 2016, at 12:27 PM, cmalk <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks great for me. Good work guys! Let me know when the "master importer" is done, then we can really start cleaning up and organizing this code. I'm getting really excited again.

**Comment by cmalk** [comment]
OK, I've broken it now. If you click on the output canvas then the vector moves as if you had clicked on the input canvas. The behavior should be: clicking on the output canvas does nothing.

Have fun!
