### ISSUE TITLE
have vector.js and target.js use only math coordinates

### ISSUE THREAD

**Issue by cmalk** [project415x/project415x.github.io#85]
This is a small issue. The code in vector.js and target.js shouldn't know how big a canvas is. So the numbers should all be in "math coordinates." The method to draw a vector should take some kind of input as to the size of the canvas. Like, perhaps even taking a canvas object as an input and using the variables for that canvas, like a method of the canvas that reports where the origin is located and what the scale is.

**Comment by SkamDart** [comment]
@cmalk I think we're safe to close this. Sauron handles everything to do with coordinates now.
